name: CI

on:
  push:
    branches: [ "master" ]
  
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master

env:
  CARGO_TERM_COLOR: auto
  PGPASSWORD: password
  DATABASE_TEST_URL: postgres://postgres:password@localhost:5432/testdb
  DATABASE_URL: postgres://postgres:password@localhost:5432/testdb
jobs:
  all-tests:
    name: Run all wallet tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev -y
          # Install sqlx-cli
          cargo install sqlx-cli --no-default-features --features native-tls,postgres
          cargo install cargo-audit
          cargo install cargo-machete

      - name: Create and prepare database
        run: |
          psql -h localhost -p 5432 -U postgres -d postgres -c 'create user testuser'
          psql -h localhost -p 5432 -U postgres -d postgres -c 'create database testdb with owner = testuser'

      - name: Run all wallet tests
        run: |
          # Test 1: wallet_is_persisted
          sqlx migrate run --source migrations/postgres
          cargo test wallet_is_persisted -- --show-output
          sqlx migrate revert --all
          
          # Test 2: test_three_wallets_list_transactions
          sqlx migrate run --source migrations/postgres
          cargo test test_three_wallets_list_transactions -- --show-output
          sqlx migrate revert --all
          
          # Test 3: wallet_load_checks
          sqlx migrate run --source migrations/postgres
          cargo test wallet_load_checks -- --show-output
          sqlx migrate revert --all
          
          # Test 4: single_descriptor_wallet_persist_and_recover
          sqlx migrate run --source migrations/postgres
          cargo test single_descriptor_wallet_persist_and_recover -- --show-output
          sqlx migrate revert --all
          
          # Test 5: two_wallets_load
          sqlx migrate run --source migrations/postgres
          cargo test two_wallets_load -- --show-output
          sqlx migrate revert --all

      - name: Check fmt and run clippy
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets -- -Dwarnings

      - name: Security Audit
        run: cargo audit

      - name: Check Unused Dependencies
        run: cargo machete